Train:
  batch_size: 1024
  train_ratio: .8
  learning_rate: 0.0001
  reg: 0.0005
  epochs: 10

network:
  model: PID_Linear 
  hidden_dim: 512
  dropout: 0.1

data:
  dataset: data//pitch_identification
  beta: .9999999
  weight_decay: 0.00001

loss:
  criterion: CE 
  optimizer: Adam 
